USE ComplexFoodDB;

CREATE TABLE Buyers(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Email NVARCHAR(255) NOT NULL,
	Password_ NVARCHAR(255) NOT NULL,
	FirstName NVARCHAR(255) NOT NULL,
	LastName NVARCHAR(255) NOT NULL,
	PhoneNumber NVARCHAR(15),
	Sex NCHAR(1),
	Confirmed TINYINT,
	Balance FLOAT,

);

CREATE TABLE Coupons(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Type NVARCHAR(255) NOT NULL,
	DateCreated DATE NOT NULL,
	UniqueCode NCHAR(6) NOT NULL,
	BuyerID INT NOT NULL FOREIGN KEY REFERENCES Buyers(ID),

);